### ISSUE TITLE
[Feature Request] Git gutter indicators (like in vscode)

### ISSUE THREAD

**Issue by adielBm** [Vinzent03/obsidian-git#810] opened 2024-11-13 09:18 UTC
this feature would make it easier to track changes directly in the editor.

This is how it looks in vscode:

![vscode](https://github.com/user-attachments/assets/1354def6-83f4-41f0-b5dc-812ef57108be)

thank you!

**Comment by Vinzent03** [comment] 2024-11-13 11:32
Duplicate of #481

**Closed by Vinzent03** 2024-11-13 11:32 UTC
