### ISSUE TITLE
[Bug]: plugin deletes notes on android due to git checkout

### ISSUE THREAD

**Issue by hannesdelbeke** [Vinzent03/obsidian-git#396] opened 2022-12-04 21:58 UTC
### Describe the bug

restarting obsidian deletes new notes when git plugin is active. 😱

It seems on restart, the git plugin checks out latest from the repo, overwriting all local unstaged changes (all new files).

### Relevant errors
No error msg

### Steps to reproduce

I make new note.
Close obsidian.
Start obsidian.
I see notification of git checkout,
After checkout is done, the new active note suddenly dissapears and is not commited. It is deleted instead.
Then more checkout notifications.

Happened all the time until i tried to make a recording next day 🤔
maybe manually committing fixed the issue. Reprod it 3 times on day of issue.

### Expected Behavior

New notes are never deleted!

### Addition context

Repo has no merge conflicts

**Workaround** 
For now i disabled the git plugin on this device, and manually commit with mgit.

**Specs**
-android 9

Git settings:
Split automatic commit N push: False
vault backup every 5 min
Auto backup after filechange True
Autopull interval 60min

Backup settings:
Pull updates on startup True
Push on backup True
Pull changes before push true

I use git oauth http, not ssh.

### Operating system

Android

### Plugin version

2.12.1

### other
Following same repro steps on windows results in expected behaviour of new notes pushed to repo. But on android notes are lost.

**Comment by Vinzent03** [comment] 2022-12-07 20:22
The commit author is not needed for push, so I doubt that's the issue.

**Comment by a1exwang** [comment] 2023-03-06 13:39
I think "setting author name and email" should be in the "Getting Started" document:
Currently it only mentions:
> Under the "Authentication/Commit Author" section, fill in the username on your git server and your password/personal access token.

Without setting author name and email, further git pull/push are blocked.

**Comment by Vinzent03** [comment] 2023-03-06 15:25
@hannesdelbeke I think your reproduce steps aren't complete. The plugin doesn't checkout anything on checkout without automatic backup/pull. May you please try the newest version 2.17.0 with exact changes of the settings?

**Comment by Vinzent03** [comment] 2023-03-07 13:03
Should be partly fixed now in 2.17.4. The issue is/was that the files were staged, because of the failed commit. Seems like the implementation of checkout in the underlying library `isomorphic-git` has a wrong implementation. It removes staged files. I don't think I'll be able to fix that though. For now I'm not doing a checkout after a merge without changes and prevent staging everything on missing author info.

**Closed as completed by Vinzent03** 2023-03-07 13:03 UTC

**Comment by jcubic** [comment] 2023-03-07 16:26
If anyone wants to contribute with a fix to isomorphic-git (linked above) you're welcome to. The library doesn't have the main author that writes all the code so if no one here is willing to contribute, the issue probably will not be solved.

**Comment by tmpmachine** [comment] 2024-03-21 04:11
@Vinzent03 After digging the issue on isomorphic-git quite a bit, there at least a way to read file content from index and replace the content on working directory.

I've added a snippet here: https://github.com/isomorphic-git/isomorphic-git/issues/1741#issuecomment-2011181973.
