### ISSUE TITLE
[Bug]: Error: Git.cwd: cannot change to non-directory

### ISSUE THREAD

**Issue by ssmmtt** [Vinzent03/obsidian-git#405] opened 2022-12-21 02:51 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/16244320/208808758-e16932e4-64ed-4fae-b1ce-9bed80c0a1fb.png)
![image](https://user-images.githubusercontent.com/16244320/208808912-7caf5698-9f52-40f2-a278-b9bdbec2fb6f.png)

Use git in msys2 of.

### Steps to reproduce

Upgrading to the latest version is no good.
There is no problem with the previous version.

### Operating system

Windows

### Plugin version

2.14.0

**Comment by Vinzent03** [comment] 2022-12-21 14:43
Can you share your plugin settings?

**Comment by ssmmtt** [comment] 2022-12-21 15:19
> Can you share your plugin settings?

![image](https://user-images.githubusercontent.com/16244320/208939661-f342e7a2-6b65-4d3a-9327-1a00fc4c15ac.png)
![image](https://user-images.githubusercontent.com/16244320/208939737-915056fe-db46-43f5-a6c8-521a8eac2721.png)

**Comment by ssmmtt** [comment] 2022-12-21 15:32
I uninstall and reinstall, and the default configuration doesn't work either.

**Comment by ssmmtt** [comment] 2022-12-21 15:49
![image](https://user-images.githubusercontent.com/16244320/208945923-fc0ba768-dca2-4abf-84f7-2e611d7070af.png)
![image](https://user-images.githubusercontent.com/16244320/208945941-72ef710a-dbed-447b-8fc8-d0e85e4ef259.png)
Version 2.6.0 can be used normally.

**Comment by Vinzent03** [comment] 2022-12-21 18:44
That is strange, may you share the output of `app.vault.adapter.basePath` in the console?

**Comment by ssmmtt** [comment] 2022-12-22 03:15
> That is strange, may you share the output of `app.vault.adapter.basePath` in the console?

![image](https://user-images.githubusercontent.com/16244320/209047834-d9cb9958-fff9-42a2-ba89-c420b3871349.png)

**Comment by lvbibir** [comment] 2023-03-31 06:16
I encountered the same problem. After re-installation of git, just restart the computer, and then Obsidian returned to normal. I guess it is caused by environmental variables.

**Comment by hartvon** [comment] 2023-08-31 06:31
Same problem, have you sovled it already?
Maybe we should install git from git-scm.com instead msys2?

**Comment by hartvon** [comment] 2023-08-31 06:54
> Same problem, have you sovled it already? Maybe we should install git from git-scm.com instead msys2?

After uninstalled git from msys2, and then resintall it from git-scm.com, the `obsidian-git` worked!
I wonder why the error occured in msys2' git version, maybe it is a bug? @Vinzent03

**Comment by ssmmtt** [comment] 2023-08-31 09:48
> 

I no longer use mysys2.

**Comment by JesusJMUJI** [comment] 2023-11-28 15:38
I apologize for necroposting, but this error has been happening to me for quite a while and would be useful if this is solved. 

I already tried the solutions on this open issue and I can't find a way to solve it. 

The error is the same as the one on the first post:
```plugin:obsidian-git:43448 
Error: Error: Git.cwd: cannot change to non-directory "/c/REPOSITORIOS/obsidian_uni"
    at GitExecutorChain.onFatalException (plugin:obsidian-git:26622:79)
    at GitExecutorChain.eval (plugin:obsidian-git:26614:24)
    at Generator.throw (<anonymous>)
    at rejected (plugin:obsidian-git:25483:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Vinzent03** [comment] 2023-11-30 15:50
@JesusJMUJI What's your custom base path option in the settings and what OS are you on?

**Comment by Vinzent03** [comment] 2023-11-30 15:57
May you as well share the output of `app.vault.adapter.basePath` in the console? I assume you are using the git version from https://git-scm.com ?

**Comment by JesusJMUJI** [comment] 2023-11-30 15:59
> May you as well share the output of `app.vault.adapter.basePath` in the console? I assume you are using the git version from https://git-scm.com ?

Here's what the console outputs:
![image](https://github.com/denolehov/obsidian-git/assets/113539857/bd418a85-cfc4-48d0-8191-ea4387d96acc)

And yes, I downloaded GIT from that website. Is there another way to download Git?

**Comment by SanderVanhove** [comment] 2023-12-02 15:36
I had this problem too. Apparently, there is an old git version installed somewhere on my Windows PC, but I can't find it to uninstall it. 

Just set the Custom Git binary path to wherever the git-scm.com one is.

`C:\Program Files\Git\bin` in my case.

![image](https://github.com/denolehov/obsidian-git/assets/18272282/21f40462-5f9f-47ac-a0c3-571d0c5cf44a)

That did the trick for me.

**Comment by JesusJMUJI** [comment] 2023-12-02 18:40
> I had this problem too. Apparently, there is an old git version installed somewhere on my Windows PC, but I can't find it to uninstall it.
> 
> Just set the Custom Git binary path to wherever the git-scm.com one is.
> 
> `C:\Program Files\Git\bin` in my case.
> 
> ![image](https://private-user-images.githubusercontent.com/18272282/287458138-21f40462-5f9f-47ac-a0c3-571d0c5cf44a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NDIzODYsIm5iZiI6MTcwMTU0MjA4NiwicGF0aCI6Ii8xODI3MjI4Mi8yODc0NTgxMzgtMjFmNDA0NjItNWY5Zi00N2FjLWEwYzMtNTcxZDBjNWNmNDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE4MzQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMmY0NTAwYzUxOTgzZWNmNjE4MzhjZmE1NDI3NDFlYTNiMTM1NDlmMTEyODE0YmIxYjBhNTExMTliNDE3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._EYPIjdY2itgcXoCaSMM2ScInORD2uN8Bpc7leAVL-I)
> 
> That did the trick for me.

Hello! I tried your proposed solution and it worked!
Many thanks! Finally I'm able to use git on obsidian again.

P.S: I put the path and the moment I was writing to say that didn't work, it seems I missed putting \git.exe on the custom path. Talk about not double-checking.

**Comment by Vinzent03** [comment] 2024-07-11 23:36
Much has changed in the handling of the base directory since creation of the issue, so I'm going to close this now. Please open a new issue if you face this again.

**Closed by Vinzent03** 2024-07-11 23:36 UTC
