### ISSUE TITLE
[Bug]: custom Git binary path using wsl doesn't work

### ISSUE THREAD

**Issue by 229c9cf0** [Vinzent03/obsidian-git#141] opened 2021-11-24 01:16 UTC
[note: suspected cause at the very end; skip ahead and come back if that's not it]

I have Git installed in WSL and added a shell script in my home that will take care of connecting to the `ssh-agent` etc. followed by actually running the requested git command. Despite the command working in both PowerShell and plain CMD, Obsidian Git reports "cannot run git command".

 *  Are you sure that the custom git binary path code actually works?
 *  If yes, what's the required format?

I have tried both `C:\Windows\System32\wsl.exe /home/REDACTED/bin/ogit` as well as just `wsl.exe /home/REDACTED/bin/ogit` or `wsl /home/REDACTED/bin/ogit` (in case there's a problem with handling backslashes...)

In CMD and PowerShell, both work:

```
C:\Users\REDACTED\Desktop\maps\obsidian>wsl /home/REDACTED/bin/ogit status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   .obsidian/plugins/obsidian-git/data.json


C:\Users\REDACTED\Desktop\maps\obsidian>C:\Windows\System32\wsl.exe /home/REDACTED/bin/ogit status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   .obsidian/plugins/obsidian-git/data.json

C:\Users\REDACTED\Desktop\maps\obsidian>C:\Windows\System32\wsl.exe /home/REDACTED/bin/ogit push
Host key fingerprint is SHA256:<redacted>
Enumerating objects: 38, done.
Counting objects: 100% (38/38), done.
Delta compression using up to 8 threads
Compressing objects: 100% (27/27), done.
Writing objects: 100% (29/29), 6.13 KiB | 184.00 KiB/s, done.
Total 29 (delta 4), reused 0 (delta 0)
To <redacted>:repos/obsidian-vault.git
   <redacted>..<redacted>  master -> master
```

In Obsidian, all variants fail.

So there seems to be some special formatting / adjustment to the command required to make it work when run from Obsidian. (Or maybe it just doesn't work at all?)

-----

While I don't really understand JS & related languages, from a quick scan of the code in [src/simpleGit.ts](https://github.com/denolehov/obsidian-git/blob/master/src/simpleGit.ts), the following seem strange:

 *  [`isGitInstalled`](https://github.com/denolehov/obsidian-git/blob/1.15.0/src/simpleGit.ts#L277), [`commitAll`](https://github.com/denolehov/obsidian-git/blob/1.15.0/src/simpleGit.ts#L79), and [`push`](https://github.com/denolehov/obsidian-git/blob/1.15.0/src/simpleGit.ts#L169) all appear to hard-code the `git` command; if `isGitInstalled` gatekeeps the running of all other commands, then it's not surprising that nothing works

**Comment by Vinzent03** [comment] 2021-11-24 06:35
I haven't tested it with wsl. I guess the problem is that you first run `wsl` and then the `git` path for wsl, but that's caused by the underlying git library. Seems to be the same issue as in [this issue](https://github.com/denolehov/obsidian-git/issues/113#issuecomment-925365823)
Regarding your guess why it doesn't work, the command use the `git` object, which is created [here](https://github.com/denolehov/obsidian-git/blob/master/src/simpleGit.ts#L20) with the path from the settings.

**Comment by 229c9cf0** [comment] 2021-11-24 09:01
But `isGitInstalled` just runs 
`spawnSync('git', ['--version'], …)` and *doesn't use the indirection*, right? (The code you linked is only reached if `isGitInstalled` returns success, so it can't have been reached yet.)

And since the indirection is **required to find git** (as it's not just `git`), *of course* it can't work.

**Comment by Vinzent03** [comment] 2021-11-25 09:13
Oh ** you are right. Definitely need to fix that. But I still doubt that it works, because the user in the other issue had a local git installation and just wanted to use the wsl installation, which didn't work. Maybe your setup is different and it works nevertheless.

**Comment by Vinzent03** [comment] 2021-11-25 09:23
Released a new version, please try it out.

**Comment by 229c9cf0** [comment] 2021-11-26 20:16
Progress! After the update, I'm getting `/bin/bash: status: command not found` which is exactly the error message that `wsl status` generates.

So it looks like something drops the second part of `wsl /home/REDACTED/bin/ogit`, and I confirmed that with an experiment. (Details below.)

For now, I added a `git.cmd` somewhere in the `%PATH%` and then wondered why it doesn't work until I found out that apparently I need to add the full `C:\...` path in spite of it being in `%PATH%` (where both cmd and powershell find & run it without problems). So now things mostly work for me!

I'd love to see the argument-dropping problem fixed _eventually_ (so I no longer need the second wrapper) but it's not urgent.

-----

Experiment: To test the argument dropping, I added symlinks named `status`, `branch`, ... in `/usr/local/bin` to _another_ wrapper that calls `/home/REDACTED/bin/ogit "$(basename "$0")" "$@"` (i.e. reroutes those program names to become a git command), such that `wsl status`, `wsl branch`, ... will work like `wsl /home/REDACTED/bin/ogit status`, .... and that confirms this guess: With that in place, I can select the branch from the drop-down in the obsidian-git config and I get a "git: ready" in the status bar, i.e. basic communication with git works. (Adding lots of other wrappers for `add`/`commit`/`push`/... means I can use the source control view to add, commit, push/pull and it all works, as verified externally.)

-----

Just for reference, in case others want my full solution for getting WSL's git working: There's a `git.cmd`

```cmd
@echo off
C:\Windows\System32\wsl.exe /home/REDACTED/bin/obsidian-git %*
```

and since `%PATH%` search doesn't work anyway, just place that anywhere and specify the full path to it as the custom command. On the Linux side, there's the `obsidian-git` wrapper that connects to the running `ssh-agent` and then calls git:

```sh
#!/bin/sh
source ${HOME}/.profile > /dev/null 2>&1 # this is where my config does the ssh-agent connecting
git "$@"
```

and in case you don't have an automated `ssh-agent` setup yet, `eval "$(keychain --eval --agents ssh)"` with `keychain` installed gets that done without lots of duplicate `ssh-agent`s. (Just `ssh-add` the key once after boot to unlock/cache it and you're done.)

**Comment by 229c9cf0** [comment] 2021-11-26 20:19
(Also I guess @maximberezin97 might want to know that there was indeed a problem and it mostly works now. Oh and thanks for the quick help too, Vinzent!)

**Comment by Vinzent03** [comment] 2021-11-26 21:14
Sorry to hear that it still doesn't work. I'm just providing the path to the [simple-git](https://github.com/steveukx/git-js) library, so it has to be an issue on their side.

I'm really thankful for your workarounds for both Windows and Linux! Should help other people facing the same issue.

**Comment by maximberezin97** [comment] 2021-11-28 01:55
> Progress! After the update, I'm getting `/bin/bash: status: command not found` which is exactly the error message that `wsl status` generates.
> 
> So it looks like something drops the second part of `wsl /home/REDACTED/bin/ogit`, and I confirmed that with an experiment. (Details below.)
> 
> For now, I added an extra `git.cmd` wrapper somewhere in the `%PATH%` and then wondered why it doesn't work until I found out that apparently I need to add the full `C:\...` path in spite of it being in `%PATH%` (where both cmd and powershell find & run it without problems). So now things mostly work for me!
> 
> I'd love to see the argument-dropping problem fixed _eventually_ (so I no longer need the second wrapper) but it's not urgent.
> 
> Experiment: To test the argument dropping, I added symlinks named `status`, `branch`, ... in `/usr/local/bin` to _another_ wrapper that calls `/home/REDACTED/bin/ogit "$(basename "$0")" "$@"` (i.e. reroutes those program names to become a git command), such that `wsl status`, `wsl branch`, ... will work like `wsl /home/REDACTED/bin/ogit status`, .... and that confirms this guess: With that in place, I can select the branch from the drop-down in the obsidian-git config and I get a "git: ready" in the status bar, i.e. basic communication with git works. (Adding lots of other wrappers for `add`/`commit`/`push`/... means I can use the source control view to add, commit, push/pull and it all works, as verified externally.)
> 
> Just for reference, in case others want my full solution for getting WSL's git working: There's a `git.cmd`
> 
> ```batchfile
> @echo off
> C:\Windows\System32\wsl.exe /home/REDACTED/bin/obsidian-git %*
> ```
> 
> and since `%PATH%` search doesn't work anyway, just place that anywhere and specify the full path to it as the custom command. On the Linux side, there's the `obsidian-git` wrapper that connects to the running `ssh-agent` and then calls git:
> 
> ```shell
> #!/bin/sh
> source ${HOME}/.profile > /dev/null 2>&1 # this is where my config does the ssh-agent connecting
> git "$@"
> ```
> 
> and in case you don't have an automated `ssh-agent` setup yet, `eval "$(keychain --eval --agents ssh)"` in e.g. your `.profile` with `keychain` installed gets that done without lots of duplicate `ssh-agent`s. (Just `ssh-add` the key once after boot to unlock/cache it and you're done.)

Thank you so much @229c9cf0 , this solution worked for me! I created the two helper files `git.cmd` and the wrapper script `obsidian-git` and set my custom Git path to `C:\Users\MyUser\git.cmd`, and had finally been able to push and pull from my Obsidian repository!

![Screenshot 2021-11-27 204449](https://user-images.githubusercontent.com/12620705/143725917-c7fbeeed-4eca-4262-804e-acb7f9f03757.png)
![Screenshot 2021-11-27 204525](https://user-images.githubusercontent.com/12620705/143725925-6b13d59d-9a2b-4a33-b0a6-bb551428c13d.png)

The hardest part was getting my `ssh-agent` to run automatically on login, but the `ssh-agent` plugin for Oh My Zsh takes care of this in one line change in my .zshrc. While this solution does appear quite fragile, it is working for the time being. I really appreciate both of your help.

**Comment by marchingon12** [comment] 2023-02-11 18:14
I created the two helper files as well, git.cmd and the wrapper script obsidian-git and set my custom Git path to C:\Users\MyUser\git.cmd.

I unfortunately get a permission denied error `zsh: permission denied /home/username/bin/obsidian-git` :( could anyone give me some tips?

**Comment by raulvasquez** [comment] 2023-09-06 22:32
I am trying to get git in WSL working but I keep getting an error 
```
plugin:obsidian-git:26622 Uncaught (in promise) Error: Error: Git.cwd: cannot change to non-directory "/mnt/c/Users/FirstName LastName/obsidian-vault"
    at GitExecutorChain.onFatalException (plugin:obsidian-git:26622:79)
    at GitExecutorChain.eval (plugin:obsidian-git:26614:24)
    at Generator.throw (<anonymous>)
    at rejected (plugin:obsidian-git:25483:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5).
```

 I setup a `git.cmd` and wrapper as `git-wrapper`. Both of these files are located in my vault. 

The contents `git.cmd` is:
```
@echo off
C:\Windows\System32\wsl.exe /mnt/c/Users/FirstName\ LastName/obsidian-vault/git-wrapper %*
``` 

and `git-wrapper` contains
```
#!/bin/sh
source ${HOME}/.profile > /dev/null 2>&1
git "$@"
```
From the command prompt in windows I can pass git commands through `git.cmd` and the same with the WSL ubuntu terminal using git-wrapper

I have the "Custom Git binary path" set to:
```
C:\Users\FirstName LastName\obsidian-vault\git.cmd
```

In the dev-console I have run `app.vault.adapter.basePath` which returns `'C:\\Users\\FirstName LastName\\obsidian-vault'

Does anyone have any ideas? The only thing I can think is the space between first and lastname in my windows Users directory is causing issues.

**Comment by Vinzent03** [comment] 2023-09-07 10:18
@raulvasquez Does the following modified snippet from the pr fix last issue?
```js
                const relativeRoot = await this.git.revparse("--show-cdup");
                relativeRoot && (await this.git.cwd(`'${relativeRoot}'`));
                ```

**Comment by Vinzent03** [comment] 2023-09-07 10:22
@raulvasquez You are using the `git.cmd` as Git Binary Path, right? Can you wrap it in `'` in the settings? That should fix the whitespace in the path issue.

**Comment by raulvasquez** [comment] 2023-09-11 20:47
> 

It cannot run the git command when I surround it in `'`. I've also tried double quotes `"` and escaping the space.

**Comment by Vinzent03** [comment] 2023-09-14 23:08
Hmm I can't get it to work as well. Seems like a bug in simpel-git to me. You'll have to use no space then.

**Comment by 229c9cf0** [comment] 2023-09-21 14:59
Haven't used Obsidian in a while, but I've looked into the current iteration of problems as well now.

When checking validity of git settings, the plugin currently runs `git -c core.quotepath=off rev-parse --show-toplevel`, which results in a path of the shape `/mnt/c/<…normal windows path…>`. It doesn't log what it's trying to do next, but whatever that is results in an `Error: Git.cwd: cannot change to non-directory /mnt/c/…` (because the `/mnt/c/` prefix is doesn't make sense on the Windows side.) This does not require whitespace or other special characters in the path components.

Apparently at some point the behavior of the plugin changed from just working with relative paths or passing paths as arguments (which works fine if Obsidian is in "Windows-land" and `git` lives in "WSL-/Linux-land") to trying to do stuff at the location of the git repository (which breaks since the absolute paths aren't the same.)

I don't have time to dig into the code, and the logs don't contain more information, so that's all I can figure out for now… But maybe that helps someone else.

**Comment by 229c9cf0** [comment] 2023-10-02 12:07
Found a silly/stupid workaround: (@raulvasquez)

In PowerShell, `cd /`, `mkdir mnt`, `cd mnt`, `junction c ..`.

That creates a folder `C:\mnt` containing a junction link back up to to `C:\`, which makes paths of the form `/mnt/c/…` work.  At that point, the current behavior of using absolute paths doesn't hurt anymore.

**Comment by H3mul** [comment] 2024-03-03 05:00
Just noticed activity on this issue - wanted to put my 2 cents since I have a working solution that satisfies me.

My motivation: I want Windows Obsidian to use WSL's git for `obsidian-git`, because my WSL has my ssh keys in the agent and also my git repo has `git-crypt` set up.

1. I have the latest  `obsidian-git` patched with #587 (just updated to latest in my [fork](https://github.com/H3mul/obsidian-git))
2. I have the Custom Git binary path setting point to `C:\Users\<user>\AppData\Local\scripts\wsl_git.cmd`
3. Contents of `wsl_git.cmd`, inspired by this thread:

```
@echo off
wsl.exe /home/<wsl user>/bin/obsidian-git %*
```

4. Contents of `bin/obsidian-git`, which ensures my env is properly set up (most importantly, the correct `SSH_AUTH_SOCK`):

```
#!/bin/bash
source ${HOME}/.profile > /dev/null 2>&1
git "$@"
```

The last one is optional, if you don't need your `.profile` you can just have `wsl_git.cmd` pointing to the wsl git binary instead.

With this setup, `obsidian-git` pulls and pushes to my remote seamlessly using my WSL auth configuration.

Hope this helps!

**Comment by Vinzent03** [comment] 2024-07-12 11:27
Some base path and git binary path issues have been fixed in the last weeks. E.g. #733. Please open a new issue if you still experience issues.

**Closed by Vinzent03** 2024-07-12 11:27 UTC

**Comment by JeuJeus** [comment] 2026-03-10 12:27
I've just stumbled across your solution @H3mul, as I'm basically facing the exact motivation for the workaround.
I.e. WSL based git-crypt for Windows based Obsidian installation.

However, I'm currently unsuccessful in deploying your approach.

As far as my understanding goes, the current upstream should already include your fixes and therefore not require any modification to the plugin itself?
