### ISSUE TITLE
[Bug]: host verification key failed

### ISSUE THREAD

**Issue by cvan20191** [Vinzent03/obsidian-git#673] opened 2024-01-14 10:52 UTC
### Describe the bug

i am trying to sync between two devices and i am getting "host verification key failed" error on the obsidian app, however everything is works if i use it through my terminal. this is just app specific. How do i fix this?

### Steps to reproduce

cmd p > git push or any connection through git in obsidian

### Operating system

Windows

### Installation Method

None

### Plugin version

2.22.1

**Comment by DistroByte** [comment] 2024-01-14 16:10
Hi, this is usually caused by git not trusting the identification of your git remote provider. Are you using Github?

You can follow [this stackoverflow post](https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository) to resolve your issue. If you have any further issues, come back!

**Comment by summer2788** [comment] 2024-03-26 17:22
same issue,
I tried all things that I can, 
also followed the solution in [this stackoverflow post](https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository)

**Comment by VerySweetBread** [comment] 2024-06-20 18:15
@DistroByte 
> however everything is works if i use it through my terminal

**Comment by Vinzent03** [comment] 2024-11-25 18:45
This issue should be resolved with v2.30.0. If you still see this happen, please create a new issue.

**Closed by Vinzent03** 2024-11-25 18:45 UTC
